apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: rainbow-hpa
  labels:
    app: rainbow
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: rainbow-deployment
  minReplicas: 3
  maxReplicas: 6
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 1
