apiVersion: v1
kind: Pod
metadata:
  name: red-pod
  labels:
    app: red
spec:
  containers:
  - name: red
    image: busybox
    command:
    - 'sh'
    - '-c'
    - 'echo Hello World!'
  restartPolicy: Never
