apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-configmap
data: 
  traefik.toml: |-
    defaultEntryPoints = ["http"]

    [entryPoints]
    [entryPoints.http]
      address = ":80"

    [kubernetes]

    [respondingTimeouts]
      idleTimeout = "300s"

    [ping]
      entrypoint = "http"
